const ANYWHERE_IN_ZONE_ONE_FARE = 2.5;
const ANY_ONE_ZONE_OUTSIDE_ZONE_ONE_FARE = 2.0;
const ANY_TWO_ZONES_INCLUDING_ZONE_ONE_FARE = 3.0;
const ANY_TWO_ZONES_EXCLUDING_ZONE_ONE_FARE = 2.25;
const ANY_BUS_JOURNEY_FARE = 1.8;
const MAX_POSSIBLE_OR_ALL_THREE_ZONES_FARE = 3.2;

const STATIONS_AND_ZONES = {
  Holborn: [1],
  EarlsCourt: [1, 2],
  Wimbledon: [3],
  Hammersmith: [2],
};

exports.ANYWHERE_IN_ZONE_ONE_FARE = ANYWHERE_IN_ZONE_ONE_FARE;
exports.ANY_ONE_ZONE_OUTSIDE_ZONE_ONE_FARE = ANY_ONE_ZONE_OUTSIDE_ZONE_ONE_FARE;
exports.ANY_TWO_ZONES_INCLUDING_ZONE_ONE_FARE = ANY_TWO_ZONES_INCLUDING_ZONE_ONE_FARE;
exports.ANY_TWO_ZONES_EXCLUDING_ZONE_ONE_FARE = ANY_TWO_ZONES_EXCLUDING_ZONE_ONE_FARE;
exports.ANY_BUS_JOURNEY_FARE = ANY_BUS_JOURNEY_FARE;
exports.MAX_POSSIBLE_OR_ALL_THREE_ZONES_FARE = MAX_POSSIBLE_OR_ALL_THREE_ZONES_FARE;
exports.STATIONS_AND_ZONES = STATIONS_AND_ZONES;
